#Image
FROM maven:3.9.9-eclipse-temurin-21-jammy AS build 
COPY . .
RUN mvn clean package -DskipTests
#Container
FROM openjdk:21-jdk
COPY --from=build /target/ems-backendDatabase-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","app.jar"]
